//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace MySample.TrainSV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="TrainSV.TrainTimeWebServiceSoap")]
    public interface TrainTimeWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationNameDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationNameDataSetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeByTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> getStationAndTimeByTrainCodeAsync(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getVersionTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getVersionTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeDataSetByTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationAndTimeDataSetByTrainCodeAsync(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeDataSetByLikeTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationAndTimeDataSetByLikeTrainCodeAsync(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getDetailInfoByTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getDetailInfoByTrainCodeAsync(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> getStationNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeByStationName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationAndTimeByStationNameAsync(string StartStation, string ArriveStation, string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrainTimeWebServiceSoapChannel : MySample.TrainSV.TrainTimeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainTimeWebServiceSoapClient : System.ServiceModel.ClientBase<MySample.TrainSV.TrainTimeWebServiceSoap>, MySample.TrainSV.TrainTimeWebServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TrainTimeWebServiceSoapClient() : 
                base(TrainTimeWebServiceSoapClient.GetDefaultBinding(), TrainTimeWebServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.TrainTimeWebServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainTimeWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TrainTimeWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), TrainTimeWebServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainTimeWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TrainTimeWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainTimeWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TrainTimeWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainTimeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationNameDataSetAsync() {
            return base.Channel.getStationNameDataSetAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> getStationAndTimeByTrainCodeAsync(string TrainCode, string UserID) {
            return base.Channel.getStationAndTimeByTrainCodeAsync(TrainCode, UserID);
        }
        
        public System.Threading.Tasks.Task<string> getVersionTimeAsync() {
            return base.Channel.getVersionTimeAsync();
        }
        
        public System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationAndTimeDataSetByTrainCodeAsync(string TrainCode, string UserID) {
            return base.Channel.getStationAndTimeDataSetByTrainCodeAsync(TrainCode, UserID);
        }
        
        public System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationAndTimeDataSetByLikeTrainCodeAsync(string TrainCode, string UserID) {
            return base.Channel.getStationAndTimeDataSetByLikeTrainCodeAsync(TrainCode, UserID);
        }
        
        public System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getDetailInfoByTrainCodeAsync(string TrainCode, string UserID) {
            return base.Channel.getDetailInfoByTrainCodeAsync(TrainCode, UserID);
        }
        
        public System.Threading.Tasks.Task<string[]> getStationNameAsync() {
            return base.Channel.getStationNameAsync();
        }
        
        public System.Threading.Tasks.Task<MySample.TrainSV.ArrayOfXElement> getStationAndTimeByStationNameAsync(string StartStation, string ArriveStation, string UserID) {
            return base.Channel.getStationAndTimeByStationNameAsync(StartStation, ArriveStation, UserID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.TrainTimeWebServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.TrainTimeWebServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://ws.webxml.com.cn/WebServices/TrainTimeWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return TrainTimeWebServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.TrainTimeWebServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return TrainTimeWebServiceSoapClient.GetEndpointAddress(EndpointConfiguration.TrainTimeWebServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            TrainTimeWebServiceSoap,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.ServiceReference.Platforms", "14.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
